//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHangHoa.Model
{
    using QLHangHoa.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon : BaseViewModel
    {


        private string _ChuThich;
        public string ChuThich { get => _ChuThich; set { _ChuThich = value; OnPropertyChanged(); } }

        private string _MaSp;
        public string MaSp { get => _MaSp; set { _MaSp = value; OnPropertyChanged(); } }

        private string _MaHoaDon;
        public string MaHoaDon { get => _MaHoaDon; set { _MaHoaDon = value; OnPropertyChanged(); } }

        private string _HoTen;
        public string HoTen { get => _HoTen; set { _HoTen = value; OnPropertyChanged(); } }


        private Nullable<int> _SoDienThoai;
        public Nullable<int> SoDienThoai { get => _SoDienThoai; set { _SoDienThoai = value; OnPropertyChanged(); } }

        private Nullable<System.DateTime> _NgayBan;
        public Nullable<System.DateTime> NgayBan { get => _NgayBan; set { _NgayBan = value; OnPropertyChanged(); } }

        private Nullable<int> _SoLuongBan;
        public Nullable<int> SoLuongBan { get => _SoLuongBan; set { _SoLuongBan = value; OnPropertyChanged(); } }

        private string _HinhThucThanhToan;
        public string HinhThucThanhToan { get => _HinhThucThanhToan; set { _HinhThucThanhToan = value; OnPropertyChanged(); } }


        public virtual SanPham SanPham { get; set; }
    }
}
