//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHangHoa.Model
{
    using QLHangHoa.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSanPham: BaseViewModel
    {
        private string _MaLoai;
        public string MaLoai { get=>_MaLoai; set { _MaLoai = value;OnPropertyChanged(); }}
        private string _TenLoai;
        public string TenLoai { get=>_TenLoai; set { _TenLoai = value;OnPropertyChanged(); }}
    }
}
